import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#dffaf3',
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 20,
  },
  title: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#21a4d6',
    textAlign: 'center',
    marginTop: 40,
  },
  middlePlaceholder: {
    marginVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  placeholderText: {
    color: '#20b265',
    fontStyle: 'italic',
    textAlign: 'center',
  },
  weatherCard: {
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 16,
    width: '100%',
    maxWidth: 320,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  weatherTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#21a4d6',
    marginBottom: 6,
  },
  weatherTemp: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#20b265',
  },
  weatherDescription: {
    fontStyle: 'italic',
    color: '#555',
  },
  weatherRecommendation: {
    marginTop: 10,
    fontWeight: '600',
    color: '#f88a3b',
  },
  weatherIcon: {
    width: 60,
    height: 60,
    marginVertical: 10,
  },
  button: {
    backgroundColor: '#f88a3b',
    paddingVertical: 14,
    paddingHorizontal: 60,
    borderRadius: 30,
    alignSelf: 'center',
    marginTop: 20,
    marginBottom: 10,
  },
  buttonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  logoHeader: {
    width: 160,
    height: 80,
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  mainContent: {
    alignItems: 'center',
    gap: 20,
    width: '100%',
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 30,
    marginBottom: 20,
    gap: 10,
  },
  titleText: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#21a4d6',
  },
  titleIcon: {
    width: 40,
    height: 40,
  },
  input: {
    height: 50,
    borderColor: '#21a4d6',
    borderWidth: 1.5,
    borderRadius: 10,
    paddingHorizontal: 15,
    backgroundColor: '#ffffff',
    color: '#000',
    width: '100%',
    maxWidth: 320,
    marginBottom: 15,
  },
  loginCard: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 16,
    width: '100%',
    maxWidth: 320,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  loginTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#21a4d6',
    marginBottom: 20,
  },
  linkText: {
    color: '#21a4d6',
    marginTop: 15,
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },

  // SPLIT BUTTON + DROPDOWN
  splitButtonRow: {
    flexDirection: 'row',
    alignSelf: 'center',
  },
  splitButtonLeft: {
    backgroundColor: '#f88a3b',
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderTopLeftRadius: 30,
    borderBottomLeftRadius: 30,
  },
  splitButtonRight: {
    backgroundColor: '#f88a3b',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderTopRightRadius: 30,
    borderBottomRightRadius: 30,
    marginLeft: 0,
  },
  splitButtonDivider: {
    width: 1,
    backgroundColor: 'white',
  },
  dropdownMenu: {
    marginTop: 8,
    backgroundColor: '#fff',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
    alignSelf: 'center',
  },
  dropdownItem: {
    paddingVertical: 8,
    color: '#21a4d6',
  },

  // NOTIFICATION
  notificationBanner: {
    marginTop: 16,
    backgroundColor: '#21a4d6',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 16,
    alignSelf: 'center',
  },
  notificationText: {
    color: 'white',
    fontWeight: 'bold',
  },
  error: {
    color: 'red',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 10,
    paddingHorizontal: 20,
  },
  success: {
    color: 'green',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 10,
    paddingHorizontal: 20,
  },
});

export default styles;
